### ISSUE TITLE
ReviewBot failed with RB 2.0.8 - ImportError: cannot import name FileAttachment

### ISSUE THREAD

**Issue by vladsf** [reviewboard/ReviewBot#16]
.. extension]# python setup.py build
running build
running build_py
running build_static_files
Error loading the extension for entry point reviewbot
Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    "Topic :: Software Development",
  File "/usr/lib/python2.7/site-packages/reviewboard/extensions/packaging.py", line 48, in setup
    setuptools_setup(**setup_kwargs)
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/djblets/extensions/packaging.py", line 268, in run
    self.run_command('build_static_files')
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/djblets/extensions/packaging.py", line 132, in run
    extension = entrypoint.load(require=False)
  File "/usr/lib/python2.7/site-packages/distribute-0.6.19-py2.7.egg/pkg_resources.py", line 1991, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/root/install/ReviewBot-master/extension/reviewbotext/extension.py", line 18, in <module>
    from reviewbotext.resources import (review_bot_review_resource,
  File "/root/install/ReviewBot-master/extension/reviewbotext/resources.py", line 16, in <module>
    from reviewboard.reviews.models import BaseComment, Review
  File "/usr/lib/python2.7/site-packages/reviewboard/reviews/models/__init__.py", line 6, in <module>
    from reviewboard.reviews.models.file_attachment_comment import \
  File "/usr/lib/python2.7/site-packages/reviewboard/reviews/models/file_attachment_comment.py", line 6, in <module>
    from reviewboard.attachments.models import FileAttachment
  File "/usr/lib/python2.7/site-packages/reviewboard/attachments/models.py", line 10, in <module>
    from reviewboard.admin.server import build_server_url
  File "/usr/lib/python2.7/site-packages/reviewboard/admin/__init__.py", line 5, in <module>
    from reviewboard.admin.widgets import increment_sync_num
  File "/usr/lib/python2.7/site-packages/reviewboard/admin/widgets.py", line 17, in <module>
    from reviewboard.attachments.models import FileAttachment
ImportError: cannot import name FileAttachment

**Comment by anselina** [comment]
This was apparently a problem with circular imports in Review Board, and should be fixed in the latest 2.0.x release. If any of you are still having this problem after upgrading Review Board, feel free to re-open the issue.
